// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ActivityItem { id: number, activity_type: string, description: string, entity_id: number | null, entity_type: string | null, timestamp: string, }