// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BackupRestoreResult { tables_restored: number, rows_restored: number, images_restored: number, }