// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryKind } from "./CategoryKind";

export interface Category { id: bigint, name: string, kind: CategoryKind, color: string | null, icon: string | null, sort_order: number, }