// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CategoryWaste { category: string, total_wasted_value: number, percentage: number, }