// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryCost } from "./CategoryCost";
import type { RecipeCost } from "./RecipeCost";
import type { SupplierCost } from "./SupplierCost";

export interface CostReport { total_spent: number, by_category: Array<CategoryCost>, by_recipe: Array<RecipeCost>, by_supplier: Array<SupplierCost>, daily_avg: number, }