// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngredientCost } from "./IngredientCost";

export interface CostBreakdown { total_cost: number, cost_per_portion: number, ingredient_costs: Array<IngredientCost>, }