// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DashboardStats { low_stock_count: bigint, expiring_soon_count: bigint, meals_this_week: bigint, total_stock_value: number, total_recipes: bigint, total_ingredients: bigint, pending_shopping_items: bigint, }