// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DashboardStats { low_stock_count: number, expiring_soon_count: number, meals_this_week: number, total_stock_value: number, total_recipes: number, total_ingredients: number, pending_shopping_items: number, }