// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditionFeature = "recipes" | "stock" | "shopping_lists" | "meal_planning" | "events" | "receipt_scanner" | "suggestions" | "waste_report" | "cost_report" | "production" | "sales" | "supplier_comparison" | "event_budget";