// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Event { id: number, name: string, event_date: string | null, notes: string | null, created_at: string, updated_at: string, }