// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EventBudget { event_id: number, event_name: string, planned_cost: number, actual_cost: number, variance: number, }