// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageEntityType } from "./ImageEntityType";

export interface Image { id: number, entity_type: ImageEntityType, entity_id: number, path: string, mime_type: string, is_primary: boolean, created_at: string, }