// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageEntityType } from "./ImageEntityType";

export interface ImageUploadInput { entity_type: ImageEntityType, entity_id: number, base64: string, mime_type: string, }