// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportIngredient } from "./ImportIngredient";
import type { ImportRecipe } from "./ImportRecipe";

export interface ImportData { version: number, ingredients: Array<ImportIngredient>, recipes: Array<ImportRecipe>, }