// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportRecipeIngredient } from "./ImportRecipeIngredient";

export interface ImportRecipe { name: string, category: string, portions: number, instructions: string, prep_time_minutes: number | null, cook_time_minutes: number | null, tags: Array<string>, ingredients: Array<ImportRecipeIngredient>, }