// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ImportResult { ingredients_created: number, ingredients_skipped: number, recipes_created: number, recipes_skipped: number, errors: Array<string>, }