// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface IngredientCost { name: string, quantity: number, unit: Unit, price_per_unit: number, total_cost: number, is_approximate: boolean, approximation_note: string | null, }