// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface IngredientInput { name: string, unit: Unit, price_per_unit: number, category: string | null, }