// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface Ingredient { id: bigint, name: string, unit: Unit, price_per_unit: number, category_id: bigint | null, favorite: boolean, created_at: string, updated_at: string, }