// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface IngredientWaste { ingredient_id: number, ingredient_name: string, unit: Unit, wasted_quantity: number, wasted_value: number, }