// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface LossInput { ingredient_id: number | null, recipe_id: number | null, quantity: number, unit: Unit, reason: string | null, }