// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MealType } from "./MealType";

export interface MealTypeStat { meal_type: MealType, count: number, total_portions: number, percentage: number, }