// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShoppingList } from "./ShoppingList";

export interface MealPlanShoppingList { shopping_list: ShoppingList, total_portions: number, recipes_used: Array<bigint>, }