// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MealPlan { id: bigint, name: string, start_date: string, end_date: string, created_at: string, updated_at: string, }