// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayOfWeek } from "./DayOfWeek";
import type { MealType } from "./MealType";

export interface MealPlanEntry { id: bigint, meal_plan_id: bigint, recipe_id: bigint, recipe_name: string, day_of_week: DayOfWeek, meal_type: MealType, portions: number, created_at: string, updated_at: string, }