// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MealPlan } from "./MealPlan";
import type { MealPlanEntry } from "./MealPlanEntry";

export interface MealPlanWithEntries { meal_plan: MealPlan, entries: Array<MealPlanEntry>, }