// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MealTypeStat } from "./MealTypeStat";
import type { RecipeMealStat } from "./RecipeMealStat";

export interface MealStats { total_meals: number, avg_portions: number, by_meal_type: Array<MealTypeStat>, by_recipe: Array<RecipeMealStat>, }