// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayOfWeek } from "./DayOfWeek";
import type { MealType } from "./MealType";

export interface MealEntryInput { recipe_id: number, day_of_week: DayOfWeek, meal_type: MealType, portions: number, }