// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface MissingIngredient { ingredient_id: bigint, ingredient_name: string, needed: number, available: number, unit: Unit, }