// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface ParsedReceiptItem { ingredient_name: string, quantity: number, unit: Unit, price_per_unit: number, total_price: number, is_discount: boolean, discount_percent: number, matched_ingredient_id: number | null, confidence: number, brand: string | null, notes: string | null, }