// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PriceQuoteInput { ingredient_id: number, supplier: string, price_per_unit: number, valid_from: string, valid_to: string, is_promo: boolean, }