// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PriceQuoteStats { ingredient_id: bigint, avg_price: number, min_price: number, max_price: number, quote_count: bigint, }