// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface PriceQuoteWithIngredient { id: number, ingredient_id: number, ingredient_name: string, ingredient_unit: Unit, supplier: string, price_per_unit: number, valid_from: string, valid_to: string, is_promo: boolean, created_at: string, }