// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockMovement } from "./StockMovement";
import type { StockShortfall } from "./StockShortfall";

export interface ProductionResult { production_id: string, movements: Array<StockMovement>, shortfalls: Array<StockShortfall>, }