// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProductionInput { recipe_id: number, multiplier: number, yields_product: boolean, reason: string | null, }