// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProxyImageResult { id: string, url: string, thumb_url: string, width: number, height: number, alt: string | null, photographer: string | null, source: string, }