// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReceiptStatus } from "./ReceiptStatus";

export interface ReceiptImport { id: number, image_path: string, raw_text: string | null, parsed_json: string | null, status: ReceiptStatus, created_at: string, }