// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedReceiptItem } from "./ParsedReceiptItem";

export interface ReceiptConfirmInput { import_id: number, items: Array<ParsedReceiptItem>, }