// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeImportIngredient } from "./RecipeImportIngredient";

export interface RecipeImportPreview { name: string, portions: number | null, instructions: string, prep_time_minutes: number | null, cook_time_minutes: number | null, image_url: string | null, ingredients: Array<RecipeImportIngredient>, }