// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockShortfall } from "./StockShortfall";

export interface RecipeSuggestion { recipe_id: number, recipe_name: string, category: string, portions: number, coverage: number, missing: Array<StockShortfall>, cost_per_portion: number, uses_expiring: boolean, }