// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface RecipeIngredient { id: bigint, recipe_id: bigint, ingredient_id: bigint, ingredient_name: string, quantity: number, unit: Unit, }