// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RecipeCost { recipe_id: number, recipe_name: string, total_cost: number, portions: number, cost_per_portion: number, count: number, }