// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface RecipeImportIngredient { raw_text: string, quantity: number, unit: Unit, name_guess: string, matched_ingredient_id: number | null, }