// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeIngredientInput } from "./RecipeIngredientInput";

export interface RecipeInput { name: string, category: string, portions: number, instructions: string, ingredients: Array<RecipeIngredientInput>, prep_time_minutes: number | null, cook_time_minutes: number | null, tags: Array<string>, image_base64: string | null, }