// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeIngredient } from "./RecipeIngredient";

export interface RecipeWithIngredients { id: number, name: string, category: string, portions: number, instructions: string, favorite: boolean, prep_time_minutes: number | null, cook_time_minutes: number | null, tags: string, image_path: string | null, created_at: string, updated_at: string, ingredients: Array<RecipeIngredient>, }