// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RecipeMealStat { recipe_id: bigint, recipe_name: string, count: number, total_portions: number, avg_portions: number, }