// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsCategory } from "./SettingsCategory";

export interface SettingsInput { key: string, value: string, category: SettingsCategory, }