// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface ShoppingItem { id: bigint, ingredient_id: bigint | null, ingredient_name: string, ingredient_unit: Unit, needed_quantity: number, stock_quantity: number, to_buy_quantity: number, category: string, estimated_cost: number, purchased: boolean, notes: string | null, purchased_at: string, created_at: string, }