// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShoppingItem } from "./ShoppingItem";

export interface ShoppingList { id: number | null, name: string, items: Array<ShoppingItem>, total_estimated_cost: number, created_at: string, }