// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShoppingListMarkPurchasedInput { list_id: number, item_id: number, quantity: number, price_per_unit: number, brand: string | null, supplier_id: number | null, notes: string | null, }