// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovementType } from "./MovementType";
import type { Unit } from "./Unit";

export interface StockMovement { id: number, ingredient_id: number | null, recipe_id: number | null, movement_type: MovementType, quantity: number, unit: Unit, unit_cost: number | null, sale_price: number | null, reason: string | null, production_id: string | null, created_by: number | null, created_at: string, }