// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StockSnapshot { date: string, ingredient_id: bigint, ingredient_name: string, quantity: number, value: number, }