// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface StockPurchaseInput { ingredient_id: number, quantity: number, unit: Unit, price_per_unit: number, total_price: number, is_discount: boolean, discount_percent: number, purchase_date: string, supplier_id: number | null, notes: string | null, }