// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface StockItemWithIngredient { id: bigint, ingredient_id: bigint, ingredient_name: string, ingredient_unit: Unit, quantity: number, min_quantity: number, price_per_unit: number, updated_at: string, }