// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface StockPurchase { id: number, ingredient_id: number, ingredient_name: string, ingredient_unit: Unit, quantity: number, unit: Unit, price_per_unit: number, total_price: number, is_discount: boolean, discount_percent: number, purchase_date: string, supplier_id: number | null, supplier_name: string | null, brand: string | null, notes: string | null, created_at: string, }