// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StockInput { ingredient_id: bigint, quantity: number, min_quantity: number, }