// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingIngredient } from "./MissingIngredient";
import type { Recipe } from "./Recipe";

export interface SuggestedRecipe { recipe: Recipe, missing_ingredients: Array<MissingIngredient>, can_make: boolean, match_percentage: number, }