// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Unit = "gram" | "kilogram" | "milligram" | "ounce" | "pound" | "milliliter" | "liter" | "fluid_ounce" | "cup" | "pint" | "quart" | "gallon" | "teaspoon" | "tablespoon" | "piece" | "dozen" | "pinch" | "bunch" | "clove" | "slice";