// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryWaste } from "./CategoryWaste";
import type { IngredientWaste } from "./IngredientWaste";

export interface WasteReport { total_wasted_value: number, by_ingredient: Array<IngredientWaste>, by_category: Array<CategoryWaste>, }